=== vojtn/nprg036-pcshop/hw3/3/xml/schemas/schema-5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="https://www.w3.org/2009/01/xml.xsd" />
    <xs:include schemaLocation="schema-1.xsd"/>
    <xs:element name="brands">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="brand">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute ref="xml:lang" use="optional" />
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="companyEmail" type="xs:string"/>
                            <xs:element name="product" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="price" type="xs:integer"/>
                                        <xs:element name="name">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute ref="xml:lang" use="optional" />
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="sale" type="xs:string"/>
                                        <xs:element name="VAT" type="xs:integer"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== vojtn/nprg036-pcshop/hw3/xml/data/data-5.xml
<?xml version="1.0" encoding="utf-8"?>
<brands>
    <brand id="schema:Brand1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema-5.xsd">
        <name>logitech</name>
        <companyEmail>support@logitech.com</companyEmail>
        <product>
            <price>50</price>
            <name>Logitech MX Keys</name>
            <sale>0</sale>
            <VAT>21</VAT>
        </product>
    </brand>
    <brand id="schema:Brand2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema-5.xsd">
        <name>AMD</name>
        <companyEmail>support@amd.com</companyEmail>
        <product>
            <price>100</price>
            <name>AMD Ryzen 5 7600</name>
            <sale>20</sale>
            <VAT>21</VAT>
        </product>
        <product>
            <price>150</price>
            <name>AMD Ryzen 7 5700X3D</name>
            <sale>20</sale>
            <VAT>21</VAT>
        </product>
    </brand>
</brands>

=== vojtn/nprg036-pcshop/hw3/3/xml/data/data-5.xml
<?xml version="1.0" encoding="utf-8"?>
<brands xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../schemas/schema-5.xsd">
    <brand id="ex:Brand1">
        <name xml:lang="en">Logitech</name>
        <companyEmail>support@logitech.com</companyEmail>
        <product id="ex:Product1">
            <price>50</price>
            <name xml:lang="en">Logitech MX Keys</name>
            <sale>0</sale>
            <VAT>21</VAT>
        </product>
    </brand>
    <brand id="ex:Brand2">
        <name xml:lang="en">AMD</name>
        <companyEmail>support@amd.com</companyEmail>
        <product id="ex:Product2">
            <price>100</price>
            <name xml:lang="en">AMD Ryzen 5 7600</name>
            <sale>20</sale>
            <VAT>21</VAT>
        </product>
        <product id="ex:Product3">
            <price>150</price>
            <name xml:lang="en">AMD Ryzen 7 5700X3D</name>
            <sale>20</sale>
            <VAT>21</VAT>
        </product>
    </brand>
    <brand id="ex:Brand3">
        <name xml:lang="en">TSMC</name>
        <companyEmail>support@tsmc.com</companyEmail>
    </brand>
</brands>
