=== vojtn/nprg036-pcshop/hw3/xml/schema-2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="customer">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"></xs:element>
                <xs:element name="email" type="xs:string"></xs:element>
                <xs:element name="registrationDate" type="xs:dateTime"></xs:element>
                <xs:element name="privileged" type="xs:boolean"></xs:element>
                <xs:element name="address">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="country" type="xs:string"/>
                            <xs:element name="city" type="xs:string" />
                            <xs:element name="streetLine" type="xs:string"/>
                            <xs:element name="postCode" type="xs:string"/>
                        </xs:sequence>     
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== vojtn/nprg036-pcshop/hw3/xml/data-2.xml
<?xml version="1.0" encoding="utf-8"?>
<customer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema-2.xsd">
    <name>Karel Novák</name>
    <email>novakk@email.cz</email>
    <registrationDate>2023-10-31T15:09:38.6875000-01:00</registrationDate>
    <privileged>false</privileged>
    <address>
    <country>Česká republika</country>
    <city>Praha</city>
    <streetLine>Malostranské náměstí 2/25</streetLine>
    <postCode>118 00</postCode>
    </address>
</customer>
