=== vojtn/nprg036-pcshop/hw3/xml/schemas/schema-4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="https://www.w3.org/2009/01/xml.xsd" />
    <xs:element name="warehouses">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="warehouse">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="capacity" type="xs:integer"/>
                            <xs:sequence>
                                <xs:element name="contact" type="xs:string"/>
                            </xs:sequence>
                                <xs:element name="address">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="country">
                                                <xs:complexType>
                                                    <xs:simpleContent>
                                                        <xs:extension base="xs:string">
                                                            <xs:attribute ref="xml:lang" use="optional" />
                                                        </xs:extension>
                                                    </xs:simpleContent>
                                                </xs:complexType>
                                            </xs:element>
                                            <xs:element name="city">
                                                <xs:complexType>
                                                    <xs:simpleContent>
                                                        <xs:extension base="xs:string">
                                                            <xs:attribute ref="xml:lang" use="optional" />
                                                        </xs:extension>
                                                    </xs:simpleContent>
                                                </xs:complexType>
                                            </xs:element>
                                            <xs:element name="streetLine">
                                                <xs:complexType>
                                                    <xs:simpleContent>
                                                        <xs:extension base="xs:string">
                                                            <xs:attribute ref="xml:lang" use="optional" />
                                                        </xs:extension>
                                                    </xs:simpleContent>
                                                </xs:complexType>
                                            </xs:element>
                                            <xs:element name="postCode">
                                                <xs:complexType>
                                                    <xs:simpleContent>
                                                        <xs:extension base="xs:string">
                                                            <xs:attribute ref="xml:lang" use="optional" />
                                                        </xs:extension>
                                                    </xs:simpleContent>
                                                </xs:complexType>
                                            </xs:element>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element name="product" minOccurs="0">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="price" type="xs:integer"/>
                                            <xs:element name="name" type="xs:string"/>
                                            <xs:element name="sale" type="xs:string"/>
                                            <xs:element name="VAT" type="xs:integer"/>
                                            <xs:element name="brand" minOccurs="0" maxOccurs="1">
                                                <xs:complexType>
                                                    <xs:sequence>
                                                        <xs:element name="name" type="xs:string"/>
                                                        <xs:element name="companyEmail" type="xs:string"/>
                                                    </xs:sequence>
                                                </xs:complexType>
                                            </xs:element>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== vojtn/nprg036-pcshop/hw3/3/xml/data/data-4.xml
<?xml version="1.0" encoding="utf-8"?>
<warehouses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../schemas/schema-4.xsd">
    <warehouse id="ex:Warehouse1">
        <capacity>9</capacity>
        <contact>warehousesupport1@ppcshop.cz</contact>
        <address id="ex:Addr2">
            <country xml:lang="en">Slovakia</country>
            <city xml:lang="en">Nitra</city>
            <streetLine xml:lang="en">Dunajska 14</streetLine>
            <postCode xml:lang="en">49411</postCode>
        </address>
        <product id="ex:Product1">
            <price>50</price>
            <name xml:lang="en">Logitech MX Keys</name>
            <sale>0</sale>
            <VAT>21</VAT>
            <brand id="ex:Brand1">
                <name xml:lang="en">Logitech</name>
                <companyEmail>support@logitech.com</companyEmail>
            </brand>
        </product>
    </warehouse>
    <warehouse id="ex:Warehouse2">
        <capacity>9</capacity>
        <address id="ex:Addr3">
            <country xml:lang="en">Czech republic</country>
            <city xml:lang="en">Praha</city>
            <streetLine xml:lang="en">Za zahradou 2</streetLine>
            <postCode xml:lang="en">16200</postCode>
        </address>
        <product id="ex:Product2">
            <price>100</price>
            <name xml:lang="en">AMD Ryzen 5 7600</name>
            <sale>20</sale>
            <VAT>21</VAT>
            <brand id="ex:Brand2">
                <name xml:lang="en">AMD</name>
                <companyEmail>support@amd.com</companyEmail>
            </brand>
        </product>
    </warehouse>
    <warehouse id="ex:Warehouse3">
        <capacity>9</capacity>
        <contact>dwad@ppcshop.cz</contact>
        <contact>warehousesupport3@ppcshop.cz</contact>
        <address id="ex:Addr3">
            <country xml:lang="en">Czech republic</country>
            <city xml:lang="en">Praha</city>
            <streetLine xml:lang="en">Za zahradou 2</streetLine>
            <postCode xml:lang="en">16200</postCode>
        </address>
        <product id="ex:Product3">
            <price>150</price>
            <name xml:lang="en">AMD Ryzen 7 5700X3D</name>
            <sale>20</sale>
            <VAT>21</VAT>
            <brand id="ex:Brand2">
                <name xml:lang="en">AMD</name>
                <companyEmail>support@amd.com</companyEmail>
            </brand>
        </product>
    </warehouse>
</warehouses>
