=== vojtn/nprg036-pcshop/hw3/xml/schemas/schema-1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">
    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="https://www.w3.org/2009/01/xml.xsd" />

    <!-- Address -->
    <xs:complexType name="addressType">
        <xs:sequence>
            <xs:element name="country">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute ref="xml:lang" use="optional" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="city">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute ref="xml:lang" use="optional" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="streetLine">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute ref="xml:lang" use="optional" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="postCode">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute ref="xml:lang" use="optional" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- Brand -->
    <xs:complexType name="brandType">
        <xs:sequence>
            <xs:element name="name">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute ref="xml:lang" use="optional" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="companyEmail" type="xs:string" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- Customer -->
    <xs:complexType name="customerType">
        <xs:sequence>
            <xs:element name="name">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute ref="xml:lang" use="optional" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="email" type="xs:string"></xs:element>
            <xs:element name="registrationDate" type="xs:dateTime"></xs:element>
            <xs:element name="identifier">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute ref="xml:lang" use="optional" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="address" type="addressType" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- Product -->
    <xs:complexType name="productType">
        <xs:sequence>
            <xs:element name="price" type="xs:integer" />
            <xs:element name="name">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute ref="xml:lang" use="optional" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="sale" type="xs:string" />
            <xs:element name="VAT" type="xs:integer" />
            <xs:element name="brand" type="brandType" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- Warehouse -->
    <xs:complexType name="warehouseType">
        <xs:sequence>
            <xs:element name="capacity" type="xs:integer" />
            <xs:sequence>
                <xs:element name="contact" type="xs:string" />
            </xs:sequence>
            <xs:element name="address" type="addressType" />
            <xs:element name="product" type="productType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- Employee -->
    <xs:complexType name="employeeType">
        <xs:sequence>
            <xs:element name="name">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute ref="xml:lang" use="optional" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="email" />
            <xs:element name="startingDate"></xs:element>
            <xs:element name="address" type="addressType" />
            <xs:element name="warehouse" type="warehouseType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <!-- Order -->
    <xs:complexType name="orderType">
        <xs:sequence>
            <xs:element name="orderNumber" type="xs:integer"></xs:element>
            <xs:element name="totalPrice" type="xs:integer"></xs:element>
            <xs:element name="customer" type="customerType" />
            <xs:element name="product" type="productType" minOccurs="1" maxOccurs="unbounded" />
            <xs:element name="address" type="addressType" />
            <xs:element name="employee" type="employeeType" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:element name="orders">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="order" type="orderType" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== vojtn/nprg036-pcshop/hw3/3/xml/data/data-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<orders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../schemas/schema-1.xsd">
    <order id="ex:Ord1">
        <orderNumber>0</orderNumber>
        <totalPrice>130</totalPrice>
        <customer id="ex:Cust1">
            <name xml:lang="en">Jo탑ko Mrkvi훾ka</name>
            <email>jozko@gmail.com</email>
            <registrationDate>1998-04-10T00:00:00Z</registrationDate>
            <identifier xml:lang="en">VIP</identifier>
            <address id="ex:Addr1">
                <country xml:lang="en">Hungary</country>
                <city xml:lang="en">Komarom</city>
                <streetLine xml:lang="en">Cajkovskeho 2</streetLine>
                <postCode xml:lang="en">16900</postCode>
            </address>
        </customer>
        <product id="ex:Product1">
            <price>50</price>
            <name xml:lang="en">Logitech MX Keys</name>
            <sale>0</sale>
            <VAT>21</VAT>
            <brand id="ex:Brand1">
                <name xml:lang="en">Logitech</name>
                <companyEmail>support@logitech.com</companyEmail>
            </brand>
        </product>
        <product id="ex:Product2">
            <price>100</price>
            <name xml:lang="en">AMD Ryzen 5 7600</name>
            <sale>20</sale>
            <VAT>21</VAT>
            <brand id="ex:Brand2">
                <name xml:lang="en">AMD</name>
                <companyEmail>support@amd.com</companyEmail>
            </brand>
        </product>
        <address id="ex:Addr1">
            <country xml:lang="en">Hungary</country>
            <city xml:lang="en">Komarom</city>
            <streetLine xml:lang="en">Cajkovskeho 2</streetLine>
            <postCode xml:lang="en">16900</postCode>
        </address>
        <employee id="ex:Emp1">
            <name xml:lang="en">Dano Drevo</name>
            <email>gabor@szekeshfehervar.sk</email>
            <startingDate>2014-02-17T00:00:00Z</startingDate>
            <address id="ex:Addr2">
                <country xml:lang="en">Slovakia</country>
                <city xml:lang="en">Nitra</city>
                <streetLine xml:lang="en">Dunajska 14</streetLine>
                <postCode xml:lang="en">49411</postCode>
            </address>
            <warehouse id="ex:Warehouse1">
                <capacity>9</capacity>
                <contact>warehousesupport1@ppcshop.cz</contact>
                <address id="ex:Addr2">
                    <country xml:lang="en">Slovakia</country>
                    <city xml:lang="en">Nitra</city>
                    <streetLine xml:lang="en">Dunajska 14</streetLine>
                    <postCode xml:lang="en">49411</postCode>
                </address>
                <product id="ex:Product1">
                    <price>50</price>
                    <name xml:lang="en">Logitech MX Keys</name>
                    <sale>0</sale>
                    <VAT>21</VAT>
                    <brand id="ex:Brand1">
                        <name xml:lang="en">Logitech</name>
                        <companyEmail>support@logitech.com</companyEmail>
                    </brand>
                </product>
            </warehouse>
            <warehouse id="ex:Warehouse2">
                <capacity>9</capacity>
                <address id="ex:Addr3">
                    <country xml:lang="en">Czech republic</country>
                    <city xml:lang="en">Praha</city>
                    <streetLine xml:lang="en">Za zahradou 2</streetLine>
                    <postCode xml:lang="en">16200</postCode>
                </address>
                <product id="ex:Product2">
                    <price>100</price>
                    <name xml:lang="en">AMD Ryzen 5 7600</name>
                    <sale>20</sale>
                    <VAT>21</VAT>
                    <brand id="ex:Brand2">
                        <name xml:lang="en">AMD</name>
                        <companyEmail>support@amd.com</companyEmail>
                    </brand>
                </product>
            </warehouse>
            <warehouse id="ex:Warehouse3">
                <capacity>9</capacity>
                <contact>mailto:dwad@ppcshop.cz</contact>
                <contact>warehousesupport3@ppcshop.cz</contact>
                <address id="ex:Addr3">
                    <country xml:lang="en">Czech republic</country>
                    <city xml:lang="en">Praha</city>
                    <streetLine xml:lang="en">Za zahradou 2</streetLine>
                    <postCode xml:lang="en">16200</postCode>
                </address>
                <product id="ex:Product3">
                    <price>150</price>
                    <name xml:lang="en">AMD Ryzen 7 5700X3D</name>
                    <sale>20</sale>
                    <VAT>21</VAT>
                    <brand id="ex:Brand2">
                        <name xml:lang="en">AMD</name>
                        <companyEmail>support@amd.com</companyEmail>
                    </brand>
                </product>
            </warehouse>
        </employee>
    </order>
    <order id="ex:Ord2">
        <orderNumber>1</orderNumber>
        <totalPrice>210</totalPrice>
        <customer id="ex:Cust1">
            <name xml:lang="en">Jo탑ko Mrkvi훾ka</name>
            <email>jozko@gmail.com</email>
            <registrationDate>1998-04-10T00:00:00Z</registrationDate>
            <identifier xml:lang="en">VIP</identifier>
            <address id="ex:Addr1">
                <country xml:lang="en">Hungary</country>
                <city xml:lang="en">Komarom</city>
                <streetLine xml:lang="en">Cajkovskeho 2</streetLine>
                <postCode xml:lang="en">16900</postCode>
            </address>
        </customer>
        <product id="ex:Product2">
            <price>100</price>
            <name xml:lang="en">AMD Ryzen 5 7600</name>
            <sale>20</sale>
            <VAT>21</VAT>
            <brand id="ex:Brand2">
                <name xml:lang="en">AMD</name>
                <companyEmail>support@amd.com</companyEmail>
            </brand>
        </product>
        <product id="ex:Product3">
            <price>150</price>
            <name xml:lang="en">AMD Ryzen 7 5700X3D</name>
            <sale>20</sale>
            <VAT>21</VAT>
            <brand id="ex:Brand2">
                <name xml:lang="en">AMD</name>
                <companyEmail>support@amd.com</companyEmail>
            </brand>
        </product>
        <address id="ex:Addr1">
            <country xml:lang="en">Hungary</country>
            <city xml:lang="en">Komarom</city>
            <streetLine xml:lang="en">Cajkovskeho 2</streetLine>
            <postCode xml:lang="en">16900</postCode>
        </address>
        <employee id="ex:Emp1">
            <name xml:lang="en">Dano Drevo</name>
            <email>gabor@szekeshfehervar.sk</email>
            <startingDate>2014-02-17T00:00:00Z</startingDate>
            <address id="ex:Addr2">
                <country xml:lang="en">Slovakia</country>
                <city xml:lang="en">Nitra</city>
                <streetLine xml:lang="en">Dunajska 14</streetLine>
                <postCode xml:lang="en">49411</postCode>
            </address>
            <warehouse id="ex:Warehouse1">
                <capacity>9</capacity>
                <contact>warehousesupport1@ppcshop.cz</contact>
                <address id="ex:Addr2">
                    <country xml:lang="en">Slovakia</country>
                    <city xml:lang="en">Nitra</city>
                    <streetLine xml:lang="en">Dunajska 14</streetLine>
                    <postCode xml:lang="en">49411</postCode>
                </address>
                <product id="ex:Product1">
                    <price>50</price>
                    <name xml:lang="en">Logitech MX Keys</name>
                    <sale>0</sale>
                    <VAT>21</VAT>
                    <brand id="ex:Brand1">
                        <name xml:lang="en">Logitech</name>
                        <companyEmail>support@logitech.com</companyEmail>
                    </brand>
                </product>
            </warehouse>
            <warehouse id="ex:Warehouse2">
                <capacity>9</capacity>
                <contact>warehousesupport2@ppcshop.cz</contact>
                <address id="ex:Addr3">
                    <country xml:lang="en">Czech republic</country>
                    <city xml:lang="en">Praha</city>
                    <streetLine xml:lang="en">Za zahradou 2</streetLine>
                    <postCode xml:lang="en">16200</postCode>
                </address>
                <product id="ex:Product2">
                    <price>100</price>
                    <name xml:lang="en">AMD Ryzen 5 7600</name>
                    <sale>20</sale>
                    <VAT>21</VAT>
                    <brand id="ex:Brand2">
                        <name xml:lang="en">AMD</name>
                        <companyEmail>support@amd.com</companyEmail>
                    </brand>
                </product>
            </warehouse>
            <warehouse id="ex:Warehouse3">
                <capacity>9</capacity>
                <contact>warehousesupport3@ppcshop.cz</contact>
                <address id="ex:Addr3">
                    <country xml:lang="en">Czech republic</country>
                    <city xml:lang="en">Praha</city>
                    <streetLine xml:lang="en">Za zahradou 2</streetLine>
                    <postCode xml:lang="en">16200</postCode>
                </address>
                <product id="ex:Product3">
                    <price>150</price>
                    <name xml:lang="en">AMD Ryzen 7 5700X3D</name>
                    <sale>20</sale>
                    <VAT>21</VAT>
                    <brand id="ex:Brand2">
                        <name xml:lang="en">AMD</name>
                        <companyEmail>support@amd.com</companyEmail>
